[package]
name = "kolme-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
jiff = { workspace = true }
kademlia-discovery = { workspace = true }
kolme = { workspace = true }
kolme-store = { workspace = true }
merkle-map = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["time"] }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
absurd-future = { workspace = true }

[target.'cfg(tokio_unstable)'.dependencies]
tokio = { workspace = true, features = ["test-util"] }

[features]
pass_through = ["kolme/pass_through"]

[lints]
workspace = true
