[package]
name = "example-six-sigma"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
cosmos = { workspace = true }
jiff = { workspace = true }
kolme = { workspace = true, features = ["pass_through"] }
reqwest = { workspace = true, features = ["json"] }
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shared = { workspace = true, features = ["realcryptography"] }
solana-keypair = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
absurd-future = { workspace = true }

[dev-dependencies]
backon = { workspace = true }
cosmwasm-std = { workspace = true }
futures-util = { workspace = true }
tempfile = { workspace = true }
tokio-tungstenite = { workspace = true }
