[package]
name = "example-solana-cosmos-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cosmos = { workspace = true }
jiff = { workspace = true }
kolme = { workspace = true, features = ["solana", "cosmwasm"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
solana-keypair = { workspace = true }
solana-pubkey = { workspace = true, features = ["serde", "std"] }
tokio = { workspace = true }
absurd-future = { workspace = true }
